name: my_profile
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.5
  intl: 
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/social_media/
    - assets/tech_stack/
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
